backend:
  name: git-gateway
  branch: main

media_folder: "/" # As fotos novas vão para a pasta principal
public_folder: "/"

collections:
  - name: "bolos"
    label: "Gerenciar Sabores"
    folder: "data/bolos" # Ele vai criar uma pastinha para salvar os dados
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nome do Bolo", name: "title", widget: "string" }
      - { label: "Foto (Nome do arquivo ex: pudim.jpg)", name: "thumbnail", widget: "string" }
      - { label: "Estoque (Quantidade)", name: "estoque", widget: "number", default: 0 }
      - { label: "Está Disponível?", name: "disponivel", widget: "boolean", default: true }
      - { label: "Previsão de Retorno (ex: Sábado)", name: "proximaData", widget: "string", required: false }